###

GET https://localhost:7168/api/superpoderes

###

POST https://localhost:7168/api/superpoderes
Content-Type: application/json

{
    "nome": "Transmutação de Matéria",
    "descricao": "Habilidade de transformar a composição molecular de objetos, convertendo um tipo de matéria em outro."
}

###
